import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import '../../../../app/theme/app_colors.dart';
import '../../../../app/theme/app_theme.dart';
import '../../../../core/domain/entities/ai_assistant_entity.dart';
import '../../../../core/utilities/app_haptics.dart';
import '../state/ai_assistant_provider.dart';

/// Full-screen immersive document reader for AI-generated financial audits & reports
class AiReportDetailScreen extends ConsumerWidget {
  final AiReportItem report;

  const AiReportDetailScreen({super.key, required this.report});

  void _shareReport(BuildContext context) {
    AppHaptics.selectionClick();
    final shareText = '''
${report.title}
Generated by EmptyPocket PocketAI (${report.providerUsed.displayName} • ${report.modelDisplayName})
Date: ${DateFormat('dd MMM yyyy, h:mm a').format(report.createdAt)}

----------------------------------------

${report.markdownContent}
''';
    SharePlus.instance.share(
      ShareParams(
        text: shareText,
        subject: report.title,
      ),
    );
  }

  void _copyMarkdown(BuildContext context) {
    AppHaptics.selectionClick();
    Clipboard.setData(ClipboardData(text: report.markdownContent));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Row(
          children: [
            Icon(Icons.check_circle_rounded, color: Colors.white, size: 18),
            SizedBox(width: 10),
            Text('Full report copied to clipboard'),
          ],
        ),
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  void _confirmDelete(BuildContext context, WidgetRef ref) {
    AppHaptics.warning();
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Row(
          children: [
            Icon(Icons.delete_outline_rounded, color: AppColors.expense),
            SizedBox(width: 8),
            Expanded(
              child: Text(
                'Delete Report?',
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
        content: Text('Delete "${report.title}"? This cannot be undone.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel'),
          ),
          FilledButton(
            style: FilledButton.styleFrom(backgroundColor: AppColors.expense),
            onPressed: () {
              ref.read(aiReportsProvider.notifier).deleteReport(report.id);
              Navigator.pop(ctx); // Close dialog
              Navigator.pop(context); // Close detail screen
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Report deleted'),
                  behavior: SnackBarBehavior.floating,
                ),
              );
            },
            child: const Text('Delete'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final financialColors = context.financialColors;
    final isDark = theme.brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(
        title: Text(
          report.title,
          style: theme.textTheme.titleMedium?.copyWith(
            fontWeight: FontWeight.w800,
          ),
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.share_outlined, size: 20),
            tooltip: 'Share Report',
            onPressed: () => _shareReport(context),
          ),
          IconButton(
            icon: const Icon(Icons.copy_rounded, size: 20),
            tooltip: 'Copy Markdown',
            onPressed: () => _copyMarkdown(context),
          ),
          PopupMenuButton<String>(
            icon: const Icon(Icons.more_vert_rounded, size: 20),
            onSelected: (action) {
              if (action == 'regenerate') {
                AppHaptics.buttonPress();
                ref.read(aiReportsProvider.notifier).regenerateReport(report.id);
                Navigator.pop(context);
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Regenerating report in background...'),
                    behavior: SnackBarBehavior.floating,
                  ),
                );
              } else if (action == 'delete') {
                _confirmDelete(context, ref);
              }
            },
            itemBuilder: (ctx) => [
              const PopupMenuItem(
                value: 'regenerate',
                child: Row(
                  children: [
                    Icon(Icons.refresh_rounded, size: 18, color: AppColors.primaryEmerald),
                    SizedBox(width: 8),
                    Text('Regenerate Report'),
                  ],
                ),
              ),
              const PopupMenuItem(
                value: 'delete',
                child: Row(
                  children: [
                    Icon(Icons.delete_outline_rounded, size: 18, color: AppColors.expense),
                    SizedBox(width: 8),
                    Text('Delete Report', style: TextStyle(color: AppColors.expense)),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(width: 4),
        ],
      ),
      body: SingleChildScrollView(
        physics: const BouncingScrollPhysics(),
        padding: const EdgeInsets.fromLTRB(20, 12, 20, 40),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Metadata Header Card
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: isDark ? AppColors.darkSurfaceVariant : AppColors.lightSurfaceVariant,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: financialColors.cardBorder),
              ),
              child: Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(10),
                    decoration: BoxDecoration(
                      color: AppColors.primaryEmerald.withAlpha(isDark ? 45 : 30),
                      shape: BoxShape.circle,
                    ),
                    child: Icon(report.type.icon, color: AppColors.primaryEmerald, size: 22),
                  ),
                  const SizedBox(width: 14),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          report.type.displayName,
                          style: const TextStyle(
                            color: AppColors.primaryEmerald,
                            fontWeight: FontWeight.w700,
                            fontSize: 12,
                            letterSpacing: 0.5,
                          ),
                        ),
                        const SizedBox(height: 2),
                        Text(
                          DateFormat('EEEE, dd MMM yyyy • h:mm a').format(report.createdAt),
                          style: TextStyle(
                            color: financialColors.textMuted,
                            fontSize: 12,
                          ),
                        ),
                        const SizedBox(height: 2),
                        Text(
                          '${report.providerUsed.displayName} • ${report.modelDisplayName}',
                          style: TextStyle(
                            color: financialColors.textMuted,
                            fontSize: 11,
                            fontStyle: FontStyle.italic,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 20),

            // Rich Markdown Body with Horizontally Scrollable Tables
            MarkdownBody(
              data: report.markdownContent,
              selectable: true,
              styleSheet: MarkdownStyleSheet.fromTheme(theme).copyWith(
                tableColumnWidth: const IntrinsicColumnWidth(),
                tableCellsPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                tableBorder: TableBorder.all(
                  color: isDark ? Colors.white24 : Colors.black12,
                  borderRadius: BorderRadius.circular(8),
                ),
                tableHead: TextStyle(
                  fontWeight: FontWeight.w800,
                  color: isDark ? Colors.white : Colors.black,
                  fontSize: 13,
                ),
                tableBody: TextStyle(
                  color: isDark ? AppColors.darkTextPrimary : AppColors.lightTextPrimary,
                  fontSize: 12.5,
                ),
                p: TextStyle(
                  fontSize: 14,
                  height: 1.6,
                  color: isDark ? AppColors.darkTextPrimary : AppColors.lightTextPrimary,
                ),
                h1: TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.w800,
                  color: isDark ? Colors.white : Colors.black,
                  height: 1.5,
                ),
                h2: TextStyle(
                  fontSize: 17,
                  fontWeight: FontWeight.w800,
                  color: isDark ? Colors.white : Colors.black,
                  height: 1.5,
                ),
                h3: TextStyle(
                  fontSize: 15,
                  fontWeight: FontWeight.w800,
                  color: isDark ? AppColors.primaryEmerald : const Color(0xFF047857),
                  height: 1.5,
                ),
                listBullet: const TextStyle(
                  color: AppColors.primaryEmerald,
                  fontWeight: FontWeight.bold,
                ),
                strong: TextStyle(
                  fontWeight: FontWeight.w800,
                  color: isDark ? AppColors.primaryEmerald : const Color(0xFF047857),
                ),
                blockquote: TextStyle(
                  color: financialColors.textMuted,
                  fontStyle: FontStyle.italic,
                  fontSize: 13.5,
                ),
                blockquoteDecoration: BoxDecoration(
                  border: const Border(
                    left: BorderSide(color: AppColors.primaryEmerald, width: 3),
                  ),
                  color: AppColors.primaryEmerald.withAlpha(isDark ? 25 : 15),
                  borderRadius: const BorderRadius.horizontal(right: Radius.circular(8)),
                ),
                code: TextStyle(
                  backgroundColor: isDark ? Colors.white10 : Colors.black12,
                  fontFamily: 'monospace',
                  fontSize: 12.5,
                ),
              ),
            ),
            const SizedBox(height: 30),

            // Bottom Quick Share / Copy Action Bar
            Row(
              children: [
                Expanded(
                  child: OutlinedButton.icon(
                    style: OutlinedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 12),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                    icon: const Icon(Icons.copy_rounded, size: 18),
                    label: const Text('Copy Markdown', style: TextStyle(fontWeight: FontWeight.w700)),
                    onPressed: () => _copyMarkdown(context),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: FilledButton.icon(
                    style: FilledButton.styleFrom(
                      backgroundColor: AppColors.primaryEmerald,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(vertical: 12),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                    icon: const Icon(Icons.share_outlined, size: 18),
                    label: const Text('Share Report', style: TextStyle(fontWeight: FontWeight.w700)),
                    onPressed: () => _shareReport(context),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
