/// Utility to automatically predict transaction category based on title or merchant keywords
class CategoryMatcher {
  static const Map<String, List<String>> _keywordMap = {
    // 1. High-priority Financial Actions & Transfers
    'Shared Expense Reimbursement': [
      'shared expense reimbursement',
      'split settlement',
      'roommate payback',
      'friend payback',
      'reimbursement',
      'dinner share',
      'bill share',
      'share payback',
      'owe payback',
      'splitwise',
      'roommate',
      'payback',
      'settle share',
    ],
    'Cashback & Refunds': [
      'reward points',
      'cred cashback',
      'gpay cashback',
      'order refund',
      'cashback',
      'reversal',
      'refund',
    ],
    'Savings Interest & FD': [
      'fixed deposit interest',
      'quarterly savings interest',
      'savings interest',
      'interest credited',
      'interest credit',
      'interest payout',
      'bank interest',
      'fixed deposit',
      'fd interest',
      'rd interest',
      'maturity',
    ],
    'Bonus & Incentives': [
      'performance bonus',
      'quarterly performance',
      'joining bonus',
      'diwali bonus',
      'appraisal',
      'incentive',
      'bonus',
    ],
    'Investments & SIP': [
      'mutual fund',
      'gold etf',
      'etf purchase',
      'gold purchase',
      'stock purchase',
      'share purchase',
      'sip installment',
      'zerodha',
      'angelone',
      'indmoney',
      'upstox',
      'stocks',
      'shares',
      'groww',
      'equity',
      'gold',
      'etf',
      'sip',
      'nps',
    ],
    'Subscriptions & Services': [
      'premium subscription',
      'monthly subscription',
      'annual subscription',
      'spotify premium',
      'youtube premium',
      'premium plan',
      'apple music',
      'subscription',
      'membership',
      'google one',
      'newspaper',
      'spotify',
      'netflix',
      'disney',
      'hotstar',
      'icloud',
      'prime',
      'maid',
      'cook',
      'gym',
    ],
    'Insurance Premiums': [
      'insurance premium',
      'health insurance',
      'term insurance',
      'bike insurance',
      'car insurance',
      'policy renewal',
      'lic premium',
      'star health',
      'hdfc ergo',
      'icici pru',
      'max life',
      'insurance',
      'policy',
      'lic',
    ],
    'Family & Home Support': [
      'money sending to home',
      'send money to home',
      'sending to home',
      'send to home',
      'home transfer',
      'house money',
      'monthly allowance',
      'allowance',
      'sent money',
      'parents',
      'village',
      'mother',
      'father',
      'family',
      'amma',
      'appa',
      'mom',
      'dad',
    ],
    'Personal Care & Wellness': [
      'cosmetics',
      'skincare',
      'grooming',
      'haircut',
      'massage',
      'parlour',
      'beauty',
      'barber',
      'salon',
      'spa',
    ],
    'Taxes & Govt Fees': [
      'property tax',
      'advance tax',
      'income tax',
      'govt fee',
      'challan',
      'gst',
      'rto',
      'tax',
    ],
    'Salary': [
      'paycheck',
      'payroll',
      'stipend',
      'salary',
      'wages',
    ],
    'Freelance': [
      'project payment',
      'client payment',
      'consulting',
      'freelance',
      'upwork',
      'fiverr',
    ],
    'Donations & Charity': [
      'relief fund',
      'donation',
      'charity',
      'temple',
      'trust',
      'gift to',
      'ngo',
    ],
    'Health & Medical': [
      'health insurance',
      'blood test',
      'pharmeasy',
      'medplus',
      'pharmacy',
      'medicine',
      'hospital',
      'optician',
      'lenskart',
      'dentist',
      'doctor',
      'apollo',
      'clinic',
      'dental',
      '1mg',
      'lab',
    ],
    'Education': [
      'stationery',
      'exam fee',
      'coursera',
      'college',
      'tuition',
      'school',
      'course',
      'udemy',
      'books',
      'fee',
    ],
    'Housing & Rent': [
      'house rent',
      'flat rent',
      'brokerage',
      'pg rent',
      'rent',
    ],
    'Bills & Utilities': [
      'electricity',
      'vi recharge',
      'water bill',
      'tata play',
      'gas bill',
      'cylinder',
      'recharge',
      'broadband',
      'bescom',
      'airtel',
      'wifi',
      'tneb',
      'mseb',
      'jio',
      'lpg',
      'dth',
      'maintenance',
    ],
    'Entertainment': [
      'bookmyshow',
      'playstation',
      'concert',
      'theatre',
      'cinema',
      'movie',
      'steam',
      'game',
      'inox',
      'pvr',
    ],
    'Transportation': [
      'metro card recharge',
      'metro recharge',
      'metro card',
      'air india',
      'fastag',
      'diesel',
      'petrol',
      'flight',
      'rapido',
      'indigo',
      'metro',
      'irctc',
      'train',
      'toll',
      'fuel',
      'uber',
      'taxi',
      'auto',
      'ola',
      'cab',
      'bus',
      'parking',
    ],
    'Groceries': [
      'nature basket',
      'supermarket',
      'bigbasket',
      'instamart',
      'vegetable',
      'blinkit',
      'veggies',
      'grocery',
      'spices',
      'ration',
      'zepto',
      'fruit',
      'dairy',
      'dmart',
      'mart',
      'milk',
    ],
    'Food & Dining': [
      'hotel food',
      'starbucks',
      'restaurant',
      'mcdonald',
      'breakfast',
      'biryani',
      'domino',
      'subway',
      'dinner',
      'burger',
      'zomato',
      'swiggy',
      'coffee',
      'bakery',
      'snack',
      'pizza',
      'lunch',
      'chai',
      'cafe',
      'dine',
      'kfc',
      'tea',
    ],
    'Shopping': [
      'electronics',
      'flipkart',
      'apparel',
      'fashion',
      'myntra',
      'meesho',
      'clothes',
      'retail shopping',
      'amazon',
      'nykaa',
      'shoes',
      'store',
      'zara',
      'ajio',
      'mall',
      'h&m',
    ],
  };

  /// Returns predicted Category name if title matches known keywords, otherwise null.
  /// Uses a longest-matching keyword algorithm with category priority ranking.
  static String? detectCategory(String title) {
    final clean = title.trim().toLowerCase();
    if (clean.isEmpty) return null;

    String? bestCategory;
    int maxMatchLength = 0;

    for (final entry in _keywordMap.entries) {
      for (final keyword in entry.value) {
        if (clean.contains(keyword)) {
          if (keyword.length > maxMatchLength) {
            maxMatchLength = keyword.length;
            bestCategory = entry.key;
          }
        }
      }
    }
    return bestCategory;
  }
}
