/// Utility to automatically predict transaction category based on title or merchant keywords
class CategoryMatcher {
  static const Map<String, List<String>> _keywordMap = {
    'Food & Dining': [
      'zomato',
      'swiggy',
      'mcdonald',
      'kfc',
      'starbucks',
      'coffee',
      'dinner',
      'lunch',
      'breakfast',
      'restaurant',
      'pizza',
      'burger',
      'subway',
      'domino',
      'cafe',
      'bakery',
      'chai',
      'tea',
      'snack',
      'biryani',
      'hotel food',
      'dine',
    ],
    'Groceries': [
      'blinkit',
      'zepto',
      'instamart',
      'bigbasket',
      'supermarket',
      'mart',
      'vegetable',
      'veggies',
      'fruit',
      'milk',
      'dairy',
      'ration',
      'grocery',
      'spices',
      'dmart',
      'nature basket',
    ],
    'Shopping': [
      'amazon',
      'flipkart',
      'myntra',
      'zara',
      'h&m',
      'clothes',
      'shoes',
      'electronics',
      'mall',
      'apparel',
      'fashion',
      'purchase',
      'store',
      'meesho',
      'ajio',
      'nykaa',
    ],
    'Transportation': [
      'uber',
      'ola',
      'rapido',
      'metro',
      'petrol',
      'fuel',
      'diesel',
      'parking',
      'toll',
      'fastag',
      'auto',
      'cab',
      'taxi',
      'bus',
      'train',
      'flight',
      'irctc',
      'indigo',
      'air india',
    ],
    'Bills & Utilities': [
      'electricity',
      'bescom',
      'tneb',
      'mseb',
      'wifi',
      'broadband',
      'water bill',
      'gas bill',
      'lpg',
      'cylinder',
      'recharge',
      'airtel',
      'jio',
      'vi recharge',
      'broadband',
      'dth',
      'tata play',
      'maintenance',
    ],
    'Entertainment': [
      'netflix',
      'spotify',
      'prime video',
      'disney',
      'hotstar',
      'movie',
      'cinema',
      'pvr',
      'inox',
      'theatre',
      'concert',
      'bookmyshow',
      'game',
      'steam',
      'playstation',
      'youtube premium',
    ],
    'Health & Medical': [
      'pharmacy',
      'medicine',
      'doctor',
      'hospital',
      'clinic',
      'lab',
      'blood test',
      'apollo',
      'medplus',
      '1mg',
      'pharmeasy',
      'dental',
      'optician',
      'lenskart',
      'dentist',
    ],
    'Education': [
      'school',
      'college',
      'tuition',
      'fee',
      'course',
      'udemy',
      'coursera',
      'books',
      'stationery',
      'exam fee',
    ],
    'Personal Care': [
      'salon',
      'barber',
      'haircut',
      'spa',
      'massage',
      'cosmetics',
      'skincare',
      'grooming',
    ],
    'Housing & Rent': [
      'rent',
      'house rent',
      'flat rent',
      'pg rent',
      'brokerage',
      'deposit',
    ],
    'Salary': [
      'salary',
      'paycheck',
      'stipend',
      'wages',
      'payroll',
    ],
    'Freelance': [
      'freelance',
      'client payment',
      'upwork',
      'fiverr',
      'consulting',
      'project payment',
    ],
    'Investments': [
      'dividend',
      'mutual fund',
      'stocks',
      'zerodha',
      'groww',
      'interest payout',
      'fd interest',
    ],
  };

  /// Returns predicted Category name if title matches known keywords, otherwise null
  static String? detectCategory(String title) {
    final clean = title.trim().toLowerCase();
    if (clean.isEmpty) return null;

    for (final entry in _keywordMap.entries) {
      for (final keyword in entry.value) {
        if (clean.contains(keyword)) {
          return entry.key;
        }
      }
    }
    return null;
  }
}
